apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nwl-authentik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://charts.goauthentik.io"
      chart: authentik
      targetRevision: "2026.8.1"
      helm:
        valueFiles:
          - $values/infrastructure/authentik/values-authentik.yaml
    - repoURL: "https://github.com/trisattawat-m/k3s-manifest.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
