grafana:
  adminPassword: "admin"
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
  extraInitContainers:
  - name: init-chmod-data
    image: busybox:latest
    command: [ "sh", "-c", "chmod -R 777 /var/lib/grafana" ]
    volumeMounts:
    - name: storage
      mountPath: /var/lib/grafana
  persistence:
    enabled: true
    size: 2Gi
    accessModes:
    - ReadWriteOnce
  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "ca-issuer"
    hosts:
    - grafana.k3s-workshop.local
    tls:
    - secretName: grafana-tls-secret
      hosts:
      - grafana.k3s-workshop.local

prometheus:
  prometheusSpec:
    retention: 3d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 5Gi
