# ============================================================================
# File: ingress/middleware.yaml
# ============================================================================
# Global middleware for path stripping (if needed globally)
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: global-stripprefix
  namespace: kube-system
spec:
  stripPrefix:
    prefixes:
      - /grafana
      - /vault
      - /nwl-wim

---
# Middleware for adding security headers
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: kube-system
spec:
  headers:
    frameDeny: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true

---
# Middleware for rate limiting
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: kube-system
spec:
  rateLimit:
    average: 100
    burst: 50
